-- 1. Таблица Марафонов
CREATE TABLE IF NOT EXISTS marathons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    access_token TEXT UNIQUE NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Участники Марафона
CREATE TABLE IF NOT EXISTS marathon_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marathon_id BIGINT REFERENCES marathons(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(telegram_id) ON DELETE CASCADE,
    start_weight NUMERIC,
    joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(marathon_id, user_id)
);

-- 3. Результаты Опросников Марафона
CREATE TABLE IF NOT EXISTS marathon_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id BIGINT REFERENCES marathon_participants(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('express', 'nutritional')),
    answers JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Обновление таблицы замеров (добавляем новые поля если их нет)
CREATE TABLE IF NOT EXISTS weekly_measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(telegram_id) ON DELETE CASCADE,
    weight NUMERIC,
    waist NUMERIC,
    chest NUMERIC,
    hips NUMERIC,
    arm_l NUMERIC,
    arm_r NUMERIC,
    leg_l NUMERIC,
    leg_r NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Если таблица weekly_measurements уже была без рук/ног, добавим их:
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'weekly_measurements' AND column_name = 'arm_l') THEN
        ALTER TABLE weekly_measurements ADD COLUMN arm_l NUMERIC;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'weekly_measurements' AND column_name = 'arm_r') THEN
        ALTER TABLE weekly_measurements ADD COLUMN arm_r NUMERIC;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'weekly_measurements' AND column_name = 'leg_l') THEN
        ALTER TABLE weekly_measurements ADD COLUMN leg_l NUMERIC;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'weekly_measurements' AND column_name = 'leg_r') THEN
        ALTER TABLE weekly_measurements ADD COLUMN leg_r NUMERIC;
    END IF;
END $$;
